name: Lint Code Base

on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Linter and Generate Report
        run: |
          echo "Running linter..." > lint_report.txt
          docker run --rm \
            -e VALIDATE_ALL_CODEBASE=true \
            -e DEFAULT_BRANCH=main \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e LINTER_RULES_PATH=.github/linter-rules \
            -v "${{ github.workspace }}:/tmp/lint" \
            -w /tmp/lint \
            ghcr.io/github/super-linter:slim:v4 >> lint_report.txt

      - name: Display Linter Report
        run: cat lint_report.txt

      - name: Upload Linter Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: lint_report.txt
