name: Lint Code Base

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: Verbeeld
        with:
          args: --log-output linter_output.txt

      - name: Display Linter Report
        run: cat linter_output.txt

      - name: Upload Linter Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linter-report
          path: linter_output.txt
