name: Release Charts

on:
  workflow_dispatch:
     inputs:
      release_version:
        description: 'Specify the release version number'
        required: true
      
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set Chart and App Versions
        run: |
          # Update the chart version and app version in Chart.yaml
          sed -i "s/^version: .*/version: ${{ github.event.inputs.release_version }}/" charts/podiumd/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: ${{ github.event.inputs.release_version }}/" charts/podiumd/Chart.yaml

      - name: Extract Open Klant Version from README.md
        id: extract_Open Klant_version
        run: |
          # Extract the version for Open Klant from README.md
          Open Klant_VERSION=$(grep -A 1 -i "Open Klant" charts/podiumd/README.md | awk '{print $2}' | head -n 1)
          
          # Verify the extracted version and set it as an output
          if [ -z "$Open Klant_VERSION" ]; then
            echo "Open Klant version not found in README.md."
            exit 1
          fi
          echo "Found Open Klant version: $Open Klant_VERSION"
          echo "::set-output name=Open Klant_version::$Open Klant_VERSION"

      - name: Fetch Open Klant Changelog for Specific Version
        id: fetch_Open Klant_changelog
        run: |
          # Define the URL to the changelog in the Open Klant repository
          Open Klant_CHANGELOG_URL="https://raw.githubusercontent.com/Open Klant/helm-charts/main/charts/promtail/CHANGELOG.md"
          
          # Fetch the changelog file
          CHANGELOG_CONTENT=$(curl -s "$Open Klant_CHANGELOG_URL")

          # Extract the changelog entry for the specific version from the dependency changelog
          Open Klant_VERSION="${{ steps.extract_Open Klant_version.outputs.Open Klant_version }}"
          VERSION_CHANGELOG=$(echo "$CHANGELOG_CONTENT" | awk "/## $Open Klant_VERSION/,/^## /" | sed '$d')

          # Verify that changelog data was retrieved
          if [ -z "$VERSION_CHANGELOG" ]; then
            echo "No changelog entry found for Open Klant version $Open Klant_VERSION."
            exit 1
          fi
          echo "Found changelog entry for Open Klant version $Open Klant_VERSION"
          echo "::set-output name=changelog::$VERSION_CHANGELOG"

      - name: Run chart-releaser with Version-Specific Changelog
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          body: |
            # Release Notes
            ### Open Klant Changelog for version ${{ steps.extract_Open Klant_version.outputs.Open Klant_version }}
            ${{ steps.fetch_Open Klant_changelog.outputs.changelog }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
