name: Create Release from Specific Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version to release (e.g., v10.4.12)'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Release Content for Specified Version
        id: get_release_content
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          TARGET_REPO="maykinmedia/open-inwoner"
          RELEASE_VERSION="${{ github.event.inputs.version }}"

          # Fetch the release content for the specified version
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$TARGET_REPO/releases")

          # Find the release with the matching version name
          RELEASE=$(echo "$RESPONSE" | jq -r ".[] | select(.name == \"$RELEASE_VERSION\")")

          # Check if the release was found
          if [ -z "$RELEASE" ]; then
            echo "Error: Release version $RELEASE_VERSION does not exist in $TARGET_REPO."
            exit 1
          fi

          # Extract the release content (body) from the response
          RELEASE_BODY=$(echo "$RELEASE" | jq -r '.body // "No release notes available for this version."')

          # Clean up the release body: Remove extra whitespace, newlines, and any unwanted characters
          CLEANED_BODY=$(echo "$RELEASE_BODY" | sed 's/\\n/ /g' | sed 's/\\r/ /g' | sed 's/\\"//g')

          # Clean any leading/trailing whitespace and handle multi-line format
          CLEANED_BODY=$(echo "$CLEANED_BODY" | sed 's/^[ \t]*//;s/[ \t]*$//' | awk 'BEGIN{RS=""; ORS="\n\n"} {print $0}')

          # Set cleaned release body in environment variable
          echo "RELEASE_BODY=$CLEANED_BODY" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: "Release ${{ github.event.inputs.version }}"
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
