name: Release Charts 

on:
  workflow_dispatch:
     inputs:
      release_version:
        description: 'Specify the release version number'
        required: true
      
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set Chart and App Versions
        run: |
          sed -i "s/^version: .*/version: ${{ github.event.inputs.release_version }}/" charts/podiumd/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: ${{ github.event.inputs.release_version }}/" charts/podiumd/Chart.yaml

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add maykinmedia https://maykinmedia.github.io/charts
          helm repo add opentelemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add wiremind https://wiremind.github.io/wiremind-helm-charts
          helm repo add dimpact https://Dimpact-Samenwerking.github.io/helm-charts
          helm repo add elastic https://helm.elastic.co
          helm repo add kiss-frontend https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/KISS-frontend/main/helm
          helm repo add kiss-adapter https://raw.githubusercontent.com/ICATT-Menselijk-Digitaal/podiumd-adapter/main/helm
          helm repo add kiss-elastic https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/.github/main/docs/scripts/elastic
          
      - name: Fetch Confluence Page Content
        id: fetch_confluence
        run: |
          # Define the public Confluence page URL
          CONFLUENCE_URL="https://dimpact.atlassian.net/wiki/spaces/PCP/pages/197984291/PodiumD+3.0+Technische+beschrijving"

          # Fetch the HTML content of the Confluence page
          CONTENT=$(curl -s "$CONFLUENCE_URL")

          # Verify that content was retrieved
          if [ -z "$CONTENT" ]; then
            echo "Failed to fetch Confluence page content."
            exit 1
          fi

          # Store the content as output, stripping HTML if desired
          PLAIN_CONTENT=$(echo "$CONTENT" | sed 's/<[^>]*>//g')
          echo "::set-output name=confluence_content::$PLAIN_CONTENT"

      - name: Run chart-releaser with Confluence Content
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          body: |
            ### Confluence Documentation
            ${{ steps.fetch_confluence.outputs.confluence_content }}
