name: Release Charts 

on:
  workflow_dispatch:
     inputs:
      release_version:
        description: 'Specify the release version number'
        required: true
      
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set Chart and App Versions
        run: |
          sed -i "s/^version: .*/version: ${{ github.event.inputs.release_version }}/" charts/podiumd/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: ${{ github.event.inputs.release_version }}/" charts/podiumd/Chart.yaml
       

      - name: Fetch changelogs from websites
        id: fetch_changelogs
        run: |
          # Fetch changelog from website 1
          WEBSITE1_CHANGELOG=$(curl -s https://open-forms.readthedocs.io/en/latest/changelog.html | head -n 20)
          
          # Fetch changelog from website 2
          WEBSITE2_CHANGELOG=$(curl -s https://github.com/open-zaak/open-zaak/blob/main/CHANGELOG.rst | head -n 20)

          # Aggregate changelogs into an environment variable
          echo "changelogs<<EOF" >> $GITHUB_ENV
          echo "### Website 1 Changelog" >> $GITHUB_ENV
          echo "$WEBSITE1_CHANGELOG" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "### Website 2 Changelog" >> $GITHUB_ENV
          echo "$WEBSITE2_CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add maykinmedia https://maykinmedia.github.io/charts
          helm repo add opentelemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add wiremind https://wiremind.github.io/wiremind-helm-charts
          helm repo add dimpact https://Dimpact-Samenwerking.github.io/helm-charts
          helm repo add elastic https://helm.elastic.co
          helm repo add kiss-frontend https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/KISS-frontend/main/helm
          helm repo add kiss-adapter https://raw.githubusercontent.com/ICATT-Menselijk-Digitaal/podiumd-adapter/main/helm
          helm repo add kiss-elastic https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/.github/main/docs/scripts/elastic
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: "Release ${{ github.event.inputs.release_version }}"
          body: |
            ## Changes in this Release
            ${{ env.commits }}
            
            ## External Changelogs
            ${{ env.changelogs }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
