name: Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull openformulieren/open-forms

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: openformulieren/open-forms
          format: table
          ignore-unfixed: true

      - name: Save Trivy report
        run: |
          echo "Generating Trivy vulnerability report..."
          docker run --rm aquasec/trivy:latest image --ignore-unfixed --format table openformulieren/open-forms > trivy_report.txt
          cat trivy_report.txt

      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-vulnerability-report
          path: trivy_report.txt
