name: Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker images
        run: |
          docker pull openformulieren/open-forms
          docker pull nginx
          docker pull openzaak/open-zaak
          docker pull openzaak/open-notificaties

      - name: Run Trivy scans and generate a single report
        run: |
          echo "Scanning openformulieren/open-forms..." > combined_report.txt
          docker run --rm aquasec/trivy:latest image --ignore-unfixed --format table openformulieren/open-forms >> combined_report.txt
          echo "" >> combined_report.txt
          echo "Scanning nginx..." >> combined_report.txt
          docker run --rm aquasec/trivy:latest image --ignore-unfixed --format table nginx >> combined_report.txt
          echo "Scanning openzaak/open-zaak..." >> combined_report.txt
          docker run --rm aquasec/trivy:latest image --ignore-unfixed --format table openzaak/open-zaak >> combined_report.txt
          echo "Scanning openzaak/open-notificaties..." >> combined_report.txt
          docker run --rm aquasec/trivy:latest image --ignore-unfixed --format table openzaak/open-notificaties >> combined_report.txt

      - name: Display combined report
        run: cat combined_report.txt

      - name: Upload combined report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-trivy-report
          path: combined_report.txt
