name: Vulnerability Sca

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull nginx

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx
