name: Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull openformulieren/open-forms

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: openformulieren/open-forms
          format: table
          ignore-unfixed: true
